#!/bin/bash
echo 'Type the name site:'
read NAME
echo 'creating folder site and template...'
sudo mkdir /var/www/$NAME
sudo touch /var/www/$NAME/index.html
sudo chmod 777 /var/www/$NAME/index.html
echo '
<html>
	<head>
	<title>'$NAME'</title>
	</head>
	<body>
		<h1>My Page is ready to edit.</h1>
	</body>
</html>
	' > /var/www/$NAME/index.html
echo 'installing needs packages...'
sudo apt install apache2 
echo 'creating & writing configs apache server...'
sudo touch /etc/apache2/sites-available/$NAME.conf
echo 'Please enter server URL( www.example.com ):'
read SERVER_LINK
export SERVER_LINK
get_value=$(python  handler.py) ; 
if [[ $get_value == 'True' ]]; then 
	echo 'continue'
else
	echo 'ERROR! please enter valid URL. Try Again'
	exit 1
fi

sudo chmod 777 /etc/apache2/sites-available/$NAME.conf
sudo echo "
<VirtualHost *:80>
# The ServerName directive sets the request scheme, hostname and port that
# the server uses to identify itself. This is used when creating
# redirection URLs. In the context of virtual hosts, the ServerName
# specifies what hostname must appear in the request's Host: header to
# match this virtual host. For the default virtual host (this file) this
# value is not decisive as it is used as a last resort host regardless.
# However, you must set it for any further virtual host explicitly.
ServerName "$SERVER_LINK"

ServerAdmin webmaster@localhost
DocumentRoot /var/www/"$NAME"

# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
# error, crit, alert, emerg.
# It is also possible to configure the loglevel for particular
# modules, e.g.
#LogLevel info ssl:warn

ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

# For most configuration files from conf-available/, which are
# enabled or disabled at a global level, it is possible to
# include a line for only one particular virtual host. For example the
# following line enables the CGI configuration for this host only
# after it has been globally disabled with 'a2disconf'.
#Include conf-available/serve-cgi-bin.conf
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
" > /etc/apache2/sites-available/$NAME.conf
echo 'setting up hosts...'
GET_IP=$(hostname -I)
sudo chmod 777 /etc/hosts
sudo echo $GET_IP $SERVER_LINK >> /etc/hosts
echo 'activating server...'
sudo a2ensite $NAME.conf
sudo service apache2 restart 
sudo systemctl reload apache2
echo 'success!'
echo 'link for your site: ' $SERVER_LINK
echo 'for edit template your site here "/var/www/'$NAME'/". '